### ISSUE TITLE
Using constant call over string override breaks CLI updating

### ISSUE THREAD

**Issue by SectOLT** [bontebok/Re-Patreonize-Me#2]
As the name implies, the CLI updater by hazre (https://github.com/hazre/ResoniteModUpdater/) checks for mod updates through a string link override, however after verification, you are calling the override string link using BuildInfo.Link and a constant, which is unsupported by the CLI Updater. As such, attempting to update your mod using this tool returns errors.

![image (54)](https://github.com/user-attachments/assets/b3a9d256-bdcf-40f9-bfc6-370e345c0beb)

If possible, remove this constant and directly put the link in the string link override so the CLI can update the mod properly.
Likewise for the version.

**Comment by bontebok** [comment]
What is the CLI updater you are referring to? I'm not familiar with this. Thanks!

**Comment by bontebok** [comment]
This should be resolved, thanks for reporting!
